import Image from 'next/image'
import { Inter } from 'next/font/google'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Woolwich Pannabai Shakha | HSS UK</title>
        <meta name="description" content="Generated by Nextjs" />
        <link rel='stylesheet' href='favicon.ico' />
      </Head>
    </div>
  )
}
