import Head from 'next/head'
import Navbar from '../components/navbar'

const Home = () => {
  return (
    <div className='min-h-screen bg-white px-0 md:px-20 lg:px-0'>
      <Head>
        <title>Woolwich Pannabai Shakha | HSS UK</title>
        <meta name="description" content="Generated by Nextjs" />
      </Head>
      <div>
        <Navbar />
        <h1 className='text-xl text-black font-bold font-burtons ml-8 tracking-wider'>Woolwich Pannabai Shakha</h1>
      </div>
    </div>
  )
}

export default Home;
